### ISSUE TITLE
Gulp.wav could not be played in Windows

### ISSUE THREAD

**Issue by Endarire** [skellytz/infinity-sounds#2]
Greetings, @skellytz!  Thankee for this GitHub 2.0 release!

I was testing various sounds from this mod and the gulp.wav didn't play in Windows, even though many other sound files did.

Thankee for fixing this!

**Comment by skellytz** [comment]
The audio files you can't open in a media player are [ACM](https://wiki.multimedia.cx/index.php/Interplay_ACM)-encoded, i.e., they are original files exported without alteration. The ones that you can open were decoded for further editing, like cleaning up compression artifacts, clipping removal, or gain adjustments.
