### ISSUE TITLE
[BG2EE] Restore BG1 PC Soundsets shouldn't use the legacy loader.

### ISSUE THREAD

**Issue by GraionDilach** [skellytz/infinity-sounds#6]
Unfortunately EE patch 2.6 broke the selection sounds on the legacy loader where they play once and then stop playing completely when the game reaches the 7th line. The only way additional voicesets reliably work on that patch level is to extend CHARSND.2da with additional coloumns (akin to how EET or https://github.com/GraionDilach/Baldurs-Gate-Voice-Pack-for-EE-2.6 does it).

Otherwise I would suggest keeping this component classic-only.

**Comment by skellytz** [comment]
Thanks! Based on the [EE Soundset Tool instructions](https://www.gibberlings3.net/forums/topic/34560-adding-soundsets-to-the-ees-using-the-ee-soundset-tool/), one would assume this only applies to the expanded soundsets. But as you read further down the thread, you guys had actually discussed and solved this issue, which I'd completely missed.

Your [Baldur's Gate Voice Pack for EE](https://github.com/GraionDilach/Baldurs-Gate-Voice-Pack-for-EE-2.6) is clearly a better choice. I'll just add it to the suggested mods section of the readme and flag this component as classic-only.
